[package]
name = "prion"
version = "0.1.0"
authors = ["?"]

[dependencies]
subprocess = "0.1.12"
winapi = { version = "0.3.4", features = ["winuser"] }
libc = "0.2.0"
bindgen = "0.32.3"
pe = "0.1.1"
bytes = "0.4.6"
byteorder = "1.2.1"